# Generated by Django 3.2 on 2023-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование или типовой код')),
                ('code', models.CharField(max_length=150, verbose_name='Код вендора')),
                ('vendor', models.CharField(choices=[('ABB', 'ABB'), ('DFS', 'Danfoss'), ('VCN', 'VACON'), ('ONI', 'ONI'), ('SNR', 'Schneider')], max_length=30)),
                ('price', models.FloatField(verbose_name='Стоимость без учёта НДС, рубли')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Количество, шт.')),
                ('amount', models.FloatField(verbose_name='Сумма без учёта НДС, рубли')),
                ('prop_id', models.TextField(verbose_name='Номер коммерческого предложения')),
                ('typecode', models.ManyToManyField(to='comcodes.TypeCode', verbose_name='Типовой код')),
            ],
        ),
    ]
