# Generated by Django 3.2 on 2023-06-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма КП, валюта')),
                ('prop_id', models.TextField(unique=True, verbose_name='Номер коммерческого предложения')),
                ('company', models.CharField(default=None, max_length=500, verbose_name='Название организации')),
                ('person', models.TextField(default=None, verbose_name='Контактное лицо')),
                ('supply_per', models.TextField(default=None, verbose_name='Срок поставки')),
                ('payment', models.TextField(default=None, verbose_name='Условия оплаты')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование или типовой код')),
                ('code', models.CharField(max_length=150, verbose_name='Код вендора')),
                ('vendor', models.CharField(choices=[('ABB', 'ABB'), ('DFS', 'Danfoss'), ('VCN', 'VACON'), ('ONI', 'ONI'), ('SNR', 'Schneider')], max_length=30)),
                ('price', models.FloatField(verbose_name='Стоимость, валюта')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCodeInProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Количество')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comcodes.proposal', verbose_name='Коммерческое предложение')),
                ('typecodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comcodes.typecode', verbose_name='Типовые коды')),
            ],
            options={
                'verbose_name': 'Типовой код в КП',
                'verbose_name_plural': 'Типовые коды в КП',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='typecodes',
            field=models.ManyToManyField(related_name='typecodes', through='comcodes.TypeCodeInProposal', to='comcodes.TypeCode', verbose_name='Типовой код'),
        ),
        migrations.AddConstraint(
            model_name='typecodeinproposal',
            constraint=models.UniqueConstraint(fields=('proposal', 'typecodes'), name='unique_proposal_typecode'),
        ),
    ]
