# Generated by Django 3.2 on 2023-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcodes', '0002_alter_proposal_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма КП, валюта'),
        ),
    ]
