# Generated by Django 3.2 on 2023-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcodes', '0003_alter_proposal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecode',
            name='vendor',
            field=models.CharField(choices=[('ABB', 'ABB'), ('Danfoss', 'Danfoss'), ('VACON', 'VACON'), ('ONI', 'ONI'), ('Schneider', 'Schneider')], max_length=30),
        ),
    ]
