# Generated by Django 3.2 on 2023-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcodes', '0004_alter_typecode_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecode',
            name='code',
            field=models.TextField(max_length=150, verbose_name='Код вендора'),
        ),
        migrations.AlterField(
            model_name='typecode',
            name='name',
            field=models.TextField(max_length=150, verbose_name='Наименование или типовой код'),
        ),
    ]
