# Generated by Django 3.2 on 2023-07-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comcodes', '0005_auto_20230627_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecodeinproposal',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typecode_in_proposals', to='comcodes.proposal', verbose_name='Коммерческое предложение'),
        ),
    ]
